### ISSUE TITLE
可以考虑出个教程

### ISSUE THREAD

**Issue by jalins** [wupeaking/vechain_helper#1]
把大体的设计思路讲一下

**Comment by wupeaking** [comment]
哪方面的教程呢？ 是flutter相关的还是区块链方向的呢？

**Comment by jalins** [comment]
> 哪方面的教程呢？ 是flutter相关的还是区块链方向的呢？

关于这个钱包的设计思路，主要是偏区块链的设计

**Comment by wupeaking** [comment]
等我有时间了考虑考虑， 现在失业再找工作。 哈哈哈 (；′⌒`)
